### ISSUE TITLE
Jupyter Notebook Error after install

### ISSUE THREAD

**Issue by jsmithe2** [openUC2/ImSwitch#71]
@beniroquai I downloaded the imswitch program with the steps through this link: https://openuc2.github.io/docs/ImSwitch/ImSwitchInstallWindows

I got an error at start-up that reads **"It appears that Jupyter Notebook isn't where it usually is. Ensure you've installed jupyter correctly and then press Ok  to find the executable jupyter-notebook"**

I already have jupyter installed and I am not sure where this should be properly located. Any ideas?

**Comment by beniroquai** [comment]
Hey @jsmithe2, sorry for my late response. A simple fix would be to install Jupyter-Notebook (e.g. `python -m install jupyter-notebook`) into your environment (I forgot to add this to the `setup.py`). You can remove the jupyter notebook extension by removing the corresponding `imnotebook`line in your config: https://github.com/openUC2/ImSwitchConfig/blob/master/config/modules.json#L5 under Documents/ImSwitchConfig/Config

**Comment by jsmithe2** [comment]
@beniroquai I installed jupyter in the imswitch miniconda environment but still the same error? I also removed the imnotebook line in the config file but that causes imswitch to not load at all? I will upload the code it gives me after deleting that extension.

**Comment by jsmithe2** [comment]
(imswitch) C:\Users\ngavu>imswitch
Traceback (most recent call last):
  File "C:\Users\ngavu\miniconda3\envs\imswitch\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ngavu\miniconda3\envs\imswitch\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ngavu\miniconda3\envs\imswitch\Scripts\imswitch.exe\__main__.py", line 4, in <module>
  File "C:\Users\ngavu\Downloads\ImSwitch\imswitch\__main__.py", line 7, in <module>
    from imswitch.imcommon.controller import ModuleCommunicationChannel, MultiModuleWindowController
  File "C:\Users\ngavu\Downloads\ImSwitch\imswitch\imcommon\controller\__init__.py", line 2, in <module>
    from .MultiModuleWindowController import MultiModuleWindowController
  File "C:\Users\ngavu\Downloads\ImSwitch\imswitch\imcommon\controller\MultiModuleWindowController.py", line 7, in <module>
    from imswitch.imcommon.model import dirtools, modulesconfigtools, ostools, APIExport
  File "C:\Users\ngavu\Downloads\ImSwitch\imswitch\imcommon\model\modulesconfigtools.py", line 81, in <module>
    _modules = _Modules.from_json(modulesFile.read(), infer_missing=True)
  File "C:\Users\ngavu\miniconda3\envs\imswitch\lib\site-packages\dataclasses_json\api.py", line 58, in from_json
    kvs = json.loads(s,
  File "C:\Users\ngavu\miniconda3\envs\imswitch\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ngavu\miniconda3\envs\imswitch\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ngavu\miniconda3\envs\imswitch\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 5 (char 67)

**Comment by beniroquai** [comment]
Hey @jsmithe2 sorry for my late reply. It looks like the json config file couldn't be parsed correctly. Can you perhaps paste it here so that I can have a look? There is a missing bracket somewhere I suppose. 

@s1alknau you got this working right? Even if jupyter is not installed no error pops up.

**Comment by s1alknau** [comment]
@jsmithe2 There is an useful online tool to validate your json file. https://jsonlint.com/
